# Generated by Django 6.0.1 on 2026-01-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_enrollment_completed_alter_enrollment_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('VIDEO', 'Video')], default='PDF', max_length=10),
        ),
        migrations.AddField(
            model_name='lesson',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/pdfs/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/videos/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('course', 'order')},
        ),
    ]
