# Generated by Django 6.0.1 on 2026-01-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='percentage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizresult',
            name='total_questions',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
